### ISSUE TITLE
jigsaw puzzle graphic 

### ISSUE THREAD

**Issue by Deris23** [dweichert/moka#28]
This idea may be too complex, but I thought of a way to simplify it. If Melinda was ok with us producing a version of her poster which was just the puzzle and not the faces, then as people pledge and we get in touch, we can ask for a photo and put it into the puzzle ourselves?

So that would be another tab called 'Finding the Others' 

And this would not need to ready for the launch - but could be added once we're starting to get pledges.

**Comment by dweichert** [comment]
Duplicated by #49
