### ISSUE TITLE
Tried to reassign the website build pledge to you 

### ISSUE THREAD

**Issue by Deris23** [dweichert/moka#43]
And it took me to a very scary page of weird text

**Comment by dweichert** [comment]
I think I just fixed this issue with the same change that fixed #40. Can you confirm? If not and you are able to reproduce the bug, please include the weird text from the scary page as it might help me to find out what goes wrong.

**Comment by Deris23** [comment]
Aha! Do the items fall in alphabetical order??

If so, can they not? How can I move the order around?

**Comment by Deris23** [comment]
Argh it's just done the same thing again - and like a complete fool I
didn't copy before I submitted. Is it because the description was too long
do you think?

**Comment by Deris23** [comment]
Hiya - basically for launch tomorrow we just need to get a screen-shot full
of pledges and then I'll really add the all properly on Monday - Cos I have
to go to sleep!

Need someone to pledge to write the pledges!

But this means changing the order, is this possible? I want it to run that
I have the idea, you build the website, michelle puts on the fundraising
cabaret, Melinda creates the image, then the poster lettering, the
crowdfund coordinator, the social media captains, the find the others
agents, then over to the more production-based asks like a venue and extras
etc.

xx D

**Comment by Deris23** [comment]
This time I tried to add item with no description and it took me here:

string(25) "Performance venue finder "

**Comment by Deris23** [comment]
yes that seems Ok - but just now I tried to add an item with an admittedly
long description and when i submitted it just said "Item must be at least
two characters long" and nothing was saved.

**Comment by dweichert** [comment]
You can change the order of the items on the user pledge list (not on the administrator's list), see Screenshot:
![pledge_list_order_by](https://cloud.githubusercontent.com/assets/2235895/19699531/f995d1f0-9af3-11e6-8e8d-d537eab7eb87.png)

**Comment by dweichert** [comment]
I am not sure how the errors occur, which you describe: _string(25) "Performance venue finder "_ and _tried to add an item with an admittedly long description and when i submitted it just said "Item must be at least
two characters long" and nothing was saved._

Probably best to show me when we have our call. Which Browser/Device do you use, e.g. PC/Mozilla Firefox v41.0.2?

**Comment by Deris23** [comment]
Safari

**Comment by Deris23** [comment]
Mac

**Comment by dweichert** [comment]
Closing this issue, after our testing last night did not reveal any defects.
