### ISSUE TITLE
signing up - bit awkward 

### ISSUE THREAD

**Issue by Deris23** [dweichert/moka#58]
Hello, in trying to sign up a few people to the site - I noticed something that is potentially irritating and off-putting: 

If you don't fill out all the obligatory boxes in the address box and then press submit - it closes the box as if you've pledged, but then your name doesn't come up next to the pledge and it's only when you go back in to the address box that you realise there are more fields you have to enter. 

Is there a way that it won't let you press submit unless all fields are captured? 

Hope that made sense.

**Comment by dweichert** [comment]
Fixed by 169586c8e6d2754cc42193879f414510a34c149c
